[build]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt-get install -y build-essential cmake perl pkg-config libclang-dev git",
    "apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross"
]

[target.armv7-unknown-linux-gnueabihf.env]
passthrough = [
    "CC_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-gcc",
    "CXX_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-g++",
    "AR_armv7_unknown_linux_gnueabihf=arm-linux-gnueabihf-ar",
    "CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc",
    "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig",
    "PKG_CONFIG_ALLOW_CROSS=1"
]
